In [1]:
#1.What is python libraries? Why do we use python libraries?
'''
Python libraries are collections of pre-written code modules that provide a wide range of functionalities to perform specific tasks. These libraries contain functions and classes that can be imported and used in your Python code to simplify development and avoid reinventing the wheel. Python libraries cover various domains such as data manipulation, scientific computing, web development, machine learning, and more.

Some popular Python libraries include:

NumPy for numerical computing
Pandas for data manipulation and analysis
Matplotlib for data visualization
Scikit-learn for machine learning
Flask for web development
Requests for making HTTP requests
Beautiful Soup for web scraping
By leveraging Python libraries, developers can save time, write cleaner code, and benefit from the expertise and optimizations provided by the library creators.
'''

'''
We use Python libraries for several reasons:

Efficiency: Python libraries provide pre-written code modules that offer ready-to-use functionalities, saving developers time and effort by avoiding the need to write code from scratch.

Specialized Functionality: Python libraries are designed to handle specific tasks or domains, such as data manipulation, scientific computing, machine learning, web development, etc. By using these libraries, developers can leverage specialized tools and algorithms tailored to their needs.

Optimization: Python libraries are often optimized for performance and efficiency, utilizing best practices and algorithms to provide fast and reliable solutions for common problems.

Community Support: Python libraries are usually maintained by a community of developers who contribute to their improvement and provide support through documentation, forums, and tutorials.

Interoperability: Python libraries are designed to work well together, allowing developers to combine functionalities from different libraries to build more complex systems or applications.

Overall, using Python libraries helps developers write better code faster, solve complex problems efficiently, and take advantage of the expertise and resources available in the Python ecosystem.
'''

'\nWe use Python libraries for several reasons:\n\nEfficiency: Python libraries provide pre-written code modules that offer ready-to-use functionalities, saving developers time and effort by avoiding the need to write code from scratch.\n\nSpecialized Functionality: Python libraries are designed to handle specific tasks or domains, such as data manipulation, scientific computing, machine learning, web development, etc. By using these libraries, developers can leverage specialized tools and algorithms tailored to their needs.\n\nOptimization: Python libraries are often optimized for performance and efficiency, utilizing best practices and algorithms to provide fast and reliable solutions for common problems.\n\nCommunity Support: Python libraries are usually maintained by a community of developers who contribute to their improvement and provide support through documentation, forums, and tutorials.\n\nInteroperability: Python libraries are designed to work well together, allowing develop

In [2]:
#2. What are the difference between the python list and array?
'''
In Python, the main differences between lists and arrays are:

Data Type:

Lists: Lists in Python can store elements of different data types within the same list.
Arrays: Arrays in Python (from the array module) can only store elements of the same data type.
Functionality:

Lists: Lists are dynamic and can grow or shrink in size. They offer a wide range of built-in functions for manipulation and iteration.
Arrays: Arrays have a fixed size and support basic array operations like element access, slicing, and manipulation.
Performance:

Lists: Lists are more versatile and easier to work with for general-purpose programming due to their flexibility.
Arrays: Arrays can be more memory efficient and faster for numerical operations, especially when using libraries like NumPy.
Usage:

Lists: Lists are commonly used for general-purpose programming where flexibility is important.
Arrays: Arrays are suitable for scenarios where a homogeneous collection of elements of the same data type is needed, especially in numerical computations.
Overall, lists are more commonly used in Python due to their flexibility and ease of use, while arrays are preferred when working with a fixed-size homogeneous collection of elements for specific tasks like numerical computing.
'''

'\nIn Python, the main differences between lists and arrays are:\n\nData Type:\n\nLists: Lists in Python can store elements of different data types within the same list.\nArrays: Arrays in Python (from the array module) can only store elements of the same data type.\nFunctionality:\n\nLists: Lists are dynamic and can grow or shrink in size. They offer a wide range of built-in functions for manipulation and iteration.\nArrays: Arrays have a fixed size and support basic array operations like element access, slicing, and manipulation.\nPerformance:\n\nLists: Lists are more versatile and easier to work with for general-purpose programming due to their flexibility.\nArrays: Arrays can be more memory efficient and faster for numerical operations, especially when using libraries like NumPy.\nUsage:\n\nLists: Lists are commonly used for general-purpose programming where flexibility is important.\nArrays: Arrays are suitable for scenarios where a homogeneous collection of elements of the same d

In [12]:
#3. Find  the sahpe, size and dimension of the following array?
import numpy as np
arr=np.array([[1,2,3,4],
     [5,6,7,8],
     [9,10,11,12]])
print(arr)
print('Dimension of the array=',arr.ndim)
print('Size of the array=',arr.size)
print('Shape of the array=',arr.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Dimension of the array= 2
Size of the array= 12
Shape of the array= (3, 4)


In [14]:
#4. Write the python code to acces the 1st  row of the following array.
arr=np.array([[1,2,3,4],
     [5,6,7,8],
     [9,10,11,12]])
print(arr[0])

[1 2 3 4]


In [15]:
#5. How do you access the element at the third row and fourth column from the given numpy array.
arr=np.array([[1,2,3,4],
     [5,6,7,8],
     [9,10,11,12]])
print(arr[2][3])

12


In [16]:
#6. Write code to extract all odd-indexed elements from the given numpy array.
arr=np.array([[1,2,3,4],
     [5,6,7,8],
     [9,10,11,12]])
odd_indexed_elements = arr[:, 1::2].flatten()
print(odd_indexed_elements)

[ 2  4  6  8 10 12]


In [1]:
#7. How can you generate a random 3x3 matrix with value between 0 and 1.
import numpy as np
random_matrix=np.random.rand(3,3)
print(random_matrix)

[[0.17046979 0.35690127 0.52821859]
 [0.68614922 0.33504779 0.73797562]
 [0.34162365 0.30892612 0.96782063]]


In [3]:
#8. Difference between np.random.rand and np.random.randn
'''
np.random.rand and np.random.randn are both functions in the NumPy library that are used to generate random numbers, but they have some key differences:

np.random.rand: This function generates random numbers from a uniform distribution over [0, 1). When you use np.random.rand, you provide the dimensions of the array you want to create as arguments. For example, np.random.rand(3, 3) would generate a 3x3 matrix of random numbers between 0 and 1.

np.random.randn: This function generates random numbers from a standard normal distribution (mean 0 and variance 1). Similarly to np.random.rand, you also provide the dimensions of the array you want to create as arguments. For example, np.random.randn(3, 3) would generate a 3x3 matrix of random numbers from a standard normal distribution.

In summary, the main difference is in the distribution of the generated random numbers: np.random.rand generates numbers from a uniform distribution over [0, 1), while np.random.randn generates numbers from a standard normal distribution with mean 0 and variance 1.
'''

'\nnp.random.rand and np.random.randn are both functions in the NumPy library that are used to generate random numbers, but they have some key differences:\n\nnp.random.rand: This function generates random numbers from a uniform distribution over [0, 1). When you use np.random.rand, you provide the dimensions of the array you want to create as arguments. For example, np.random.rand(3, 3) would generate a 3x3 matrix of random numbers between 0 and 1.\n\nnp.random.randn: This function generates random numbers from a standard normal distribution (mean 0 and variance 1). Similarly to np.random.rand, you also provide the dimensions of the array you want to create as arguments. For example, np.random.randn(3, 3) would generate a 3x3 matrix of random numbers from a standard normal distribution.\n\nIn summary, the main difference is in the distribution of the generated random numbers: np.random.rand generates numbers from a uniform distribution over [0, 1), while np.random.randn generates numb

In [5]:
#9. Write code to increase the dimension of the following array?
arr=np.array([[1,2,3,4],
     [5,6,7,8],
     [9,10,11,12]])
new_arr = np.expand_dims(arr, axis=0)
print(arr)
print(new_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [9]:
#10. How to transpose the following array in numpy?
import numpy as np
arr=np.array([[1,2,3,4],
     [5,6,7,8],
     [9,10,11,12]])
print(arr.T)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [20]:
#11. Consider the following matrix
import numpy as np
A=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
B=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
#1. Index wise multiplication
print(A*B)
#2. Matrix multiplication
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

B = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12]])
print(np.dot(A,B))

#3. Add both matrix
A=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
B=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(A+B)
#4. Subtract matrix B from matrix A
print(A-B)

#5. Devide matrix B by matrix A
print(B/A)

[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
[[ 70  80  90]
 [158 184 210]
 [246 288 330]]
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [22]:
#12. Which function in numpy can be used to swap the byte order of an array?
arr = np.array([1, 2, 3, 4], dtype=np.int32)
arr_swapped = arr.byteswap()
print(arr)
print(arr_swapped)

[1 2 3 4]
[16777216 33554432 50331648 67108864]


In [26]:
#13. What is the significance of the np.linalg.inv function?
'''
The np.linalg.inv function in NumPy is used to compute the inverse of a square matrix. The significance of the np.linalg.inv function lies in its ability to find the inverse of a matrix, which is crucial in various mathematical and scientific computations, such as solving systems of linear equations, calculating determinants, and performing various transformations.

Here are some key points regarding the significance of the np.linalg.inv function:


Orthogonal Matrices: For orthogonal matrices, the inverse is equal to the transpose. This property is often utilized in various numerical computations.

Numerical Stability: In numerical computations, matrix inversion can sometimes be numerically unstable due to floating-point errors. The np.linalg.inv function in NumPy provides a reliable and optimized implementation for computing the inverse of a matrix.

Overall, the np.linalg.inv function is significant as it enables users to perform various mathematical operations that require the computation of the inverse of a square matrix efficiently and accurately.
'''

'\nThe np.linalg.inv function in NumPy is used to compute the inverse of a square matrix. The significance of the np.linalg.inv function lies in its ability to find the inverse of a matrix, which is crucial in various mathematical and scientific computations, such as solving systems of linear equations, calculating determinants, and performing various transformations.\n\nHere are some key points regarding the significance of the np.linalg.inv function:\n\n\nOrthogonal Matrices: For orthogonal matrices, the inverse is equal to the transpose. This property is often utilized in various numerical computations.\n\nNumerical Stability: In numerical computations, matrix inversion can sometimes be numerically unstable due to floating-point errors. The np.linalg.inv function in NumPy provides a reliable and optimized implementation for computing the inverse of a matrix.\n\nOverall, the np.linalg.inv function is significant as it enables users to perform various mathematical operations that requ

In [24]:
#14. What does the np.reshape function do, and how is it used? 
'''The np.reshape function in NumPy is used to change the shape of an array without changing its data. It allows you to reorganize the elements of an array into a new shape while maintaining the same data. This function does not modify the original array; instead, it returns a new view of the data with the desired shape.

Here's how the np.reshape function is used:

Syntax: The syntax of the np.reshape function is as follows:

python
Copy
np.reshape(a, newshape, order='C')
a: The array that you want to reshape.
newshape: The new shape that you want to give to the array. It can be a tuple specifying the dimensions of the new shape.
order: (Optional) Specifies the order in which elements are read from and written to the reshaped array. It can be 'C' (row-major, default) or 'F' (column-major).
Example:'''

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = np.reshape(arr, (2, 3))
print(reshaped_arr)

'''In this example, we create a 1D array arr with 6 elements. By using np.reshape(arr, (2, 3)), we reshape the array into a 2x3 matrix. The resulting reshaped_arr will be a new view of the data with the shape (2, 3).

Usage:

Reshaping arrays for compatibility with specific functions or operations.
Converting between different dimensionalities of arrays.
Preparing data for input into machine learning models that require specific input shapes.
Overall, the np.reshape function is a powerful tool in NumPy that allows for flexible manipulation of array shapes without modifying the underlying data, enabling efficient data manipulation and transformation in various scientific computing tasks.'''

[[1 2 3]
 [4 5 6]]


'In this example, we create a 1D array arr with 6 elements. By using np.reshape(arr, (2, 3)), we reshape the array into a 2x3 matrix. The resulting reshaped_arr will be a new view of the data with the shape (2, 3).\n\nUsage:\n\nReshaping arrays for compatibility with specific functions or operations.\nConverting between different dimensionalities of arrays.\nPreparing data for input into machine learning models that require specific input shapes.\nOverall, the np.reshape function is a powerful tool in NumPy that allows for flexible manipulation of array shapes without modifying the underlying data, enabling efficient data manipulation and transformation in various scientific computing tasks.'

In [25]:
#15. What is broadcasting in numpy?
'''Broadcasting in NumPy is a powerful mechanism that allows arrays of different shapes to be combined in arithmetic operations. When you perform operations on arrays with different shapes, NumPy automatically "broadcasts" the arrays to make their shapes compatible for the operation. This broadcasting behavior eliminates the need for explicit loops and simplifies the syntax of array operations.

Key points about broadcasting in NumPy include:

Rules of Broadcasting:

If the arrays have a different number of dimensions, the shape of the array with fewer dimensions is padded with ones on its left side.
The sizes of the corresponding dimensions of the two arrays are compared. Two dimensions are compatible when:
They are equal.
One of them is 1.
If the sizes of the corresponding dimensions are not equal and none of them is 1, then a "ValueError" is raised, indicating that the arrays are not broadcastable.
'''

A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([10, 20, 30])
result = A + B
print(result)

'''In this example, array A has a shape of (2, 3), and array B has a shape of (3,). When performing the operation A + B, NumPy broadcasts array B to the shape (2, 3) by duplicating its values along the rows. The result is an element-wise addition of A and the broadcasted B.

Benefits:

Simplifies syntax: You can perform operations on arrays of different shapes without explicitly reshaping them.
Improves performance: Broadcasting allows NumPy to optimize memory usage and avoid unnecessary copying of data.
Broadcasting is a fundamental feature in NumPy that enables efficient vectorized operations on arrays with different shapes, making it a powerful tool for array manipulation and computation in scientific computing and data analysis tasks.'''

[[11 22 33]
 [14 25 36]]


'In this example, array A has a shape of (2, 3), and array B has a shape of (3,). When performing the operation A + B, NumPy broadcasts array B to the shape (2, 3) by duplicating its values along the rows. The result is an element-wise addition of A and the broadcasted B.\n\nBenefits:\n\nSimplifies syntax: You can perform operations on arrays of different shapes without explicitly reshaping them.\nImproves performance: Broadcasting allows NumPy to optimize memory usage and avoid unnecessary copying of data.\nBroadcasting is a fundamental feature in NumPy that enables efficient vectorized operations on arrays with different shapes, making it a powerful tool for array manipulation and computation in scientific computing and data analysis tasks.'